name: auto_updater_platform_interface
description: A common platform interface for the auto_updater plugin.
version: 0.2.0
homepage: https://github.com/leanflutter/auto_updater/blob/main/packages/auto_updater_platform_interface

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1
